" author @holman

" Install pathogen things
execute pathogen#infect()

syntax on
filetype plugin indent on

set nu
set rnu
set ruler
set autoindent
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
set hlsearch " Highlight search patterns
set ignorecase
set smartcase
set visualbell " Flash screen instead of sounding beep
set colorcolumn=80
set backspace=indent,eol,start
set backupcopy=yes
set mouse=r

colorscheme solarized

set bg=light

let g:ctrlp_max_files=0
let g:ctrlp_custom_ignore = '\v[\/](build|coverage|bower_components|tmp|node_modules|target|dist|flow-typed|uploads)\/|(\.(swp|ico|git|svn|pyc))$'

let g:jsx_ext_required = 0
let g:javascript_plugin_flow = 1

" For Google Copilot
highlight CopilotSuggestion guifg=#00aaaa ctermfg=8

" Indent settings for makefile
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0

" Automatically cd into the directory that the file is in
autocmd BufEnter * execute "chdir ".escape(expand("%:p:h"), ' ')

augroup filetype
  au BufNewFile,BufRead *.eliom set filetype=ocaml
  au BufNewFile,BufRead *.inc set filetype=php
  au BufNewFile,BufRead *.ejs set filetype=html
  au BufNewFile,BufRead *.template set filetype=jinja
  au BufNewFile,BufRead *.mjml set filetype=html
  au BufNewFile,BufRead *.inky set filetype=eruby.html
augroup END

" Bash like tab completion
set wildmenu
set wildmode=list:longest

" Remove any trailing whitespace that is in the file
autocmd BufRead,BufWrite * if (! &bin && &ft != 'markdown') | silent! %s/\s\+$//ge | endif

" Ignore python # smartindent
:inoremap # X#
