" author @holman

" Install pathogen things
execute pathogen#infect()

syntax on
filetype plugin indent on

set nu
set rnu
set ruler
set autoindent
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
set hlsearch " Highlight search patterns
set ignorecase
set smartcase
set visualbell " Flash screen instead of sounding beep
set colorcolumn=80
set backspace=indent,eol,start
colorscheme solarized

set bg=dark

let g:ctrlp_max_files=0
let g:ctrlp_custom_ignore = '\v[\/](build|third_party|coverage|bower_components|tmp|node_modules|target|dist)|(\.(swp|ico|git|svn))$'

" Automatically enter NODETree
" autocmd VimEnter * NERDTree
" autocmd VimEnter * if argc() | wincmd w | endif

" Indent settings for makefile
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0

" Automatically cd into the directory that the file is in
autocmd BufEnter * execute "chdir ".escape(expand("%:p:h"), ' ')

augroup filetype
  au BufNewFile,BufRead *.eliom set filetype=ocaml
  au BufNewFile,BufRead *.inc,*.html set filetype=php
  au BufNewFile,BufRead *.template set filetype=jinja
augroup END

" Bash like tab completion
set wildmenu
set wildmode=list:longest

" Remove any trailing whitespace that is in the file
autocmd BufRead,BufWrite * if ! &bin | silent! %s/\s\+$//ge | endif

" Ignore python # smartindent
:inoremap # X#
