# @author holman
#
# Edited version of solarized color scheme (copies the 8 color sequence
#  twice so it looks pretty in Vim)
#
# Install in /usr/share/xfce4/terminal/colorschemes/

[Scheme]
Name=My Solarized Light
ColorForeground=#002B36
ColorBackground=#fdf6e3
ColorCursor=#93a1a1
TabActivityColor=#dc322f
ColorPalette=#073642;#dc322f;#859900;#b58900;#2680d2;#d33682;#2aa198;#eee8d5;#002b36;#cb4b16;#65fb83;#586e75;#93a1a1;#6c71c4;#839496;#fdf6e3
ColorBold=#93a1a1
ColorBoldUseDefault=FALSE
